Repository YAPP-Github/20th-Web-Team-1-FE, pull requests merged in 2022-08, with the labels that each got.

#147 [#146] Fix : svg 블러 현상 개선 ,totalMessage에러로 인한 수정
  src/assets/images/appBackground/orange_bee.png
  src/assets/images/appBackground/orange_bee.svg
  src/assets/images/messages/delete_icon.png
  src/assets/images/messages/delete_icon.svg
  src/assets/images/messages/empty_box_bee.png
  src/assets/images/messages/empty_box_bee.svg
  src/assets/images/messages/empty_folder_bee.png
  src/assets/images/messages/empty_folder_bee.svg
  src/assets/images/messages/message_bee.svg
  src/assets/images/noticeTree/alert_bee.png
  src/assets/images/noticeTree/alert_bee.svg
  src/assets/images/noticeTree/no_message.png
  src/assets/images/noticeTree/no_message.svg
  src/assets/images/noticeTree/watering_icon.png
  src/assets/images/noticeTree/watering_icon.svg
  src/assets/images/shared/main_bee.png
  src/assets/images/trees/apple.png
  src/assets/images/trees/apple.svg
  src/assets/images/trees/blueberry.png
  src/assets/images/trees/blueberry.svg
  src/assets/images/trees/grape.png
  src/assets/images/trees/grape.svg
  src/assets/images/trees/lemon.png
  src/assets/images/trees/lemon.svg
  src/assets/images/trees/orange.png
  src/assets/images/trees/orange.svg
  src/assets/images/trees/strawberry.png
  src/assets/images/trees/strawberry.svg
  src/components/features/Forest/TreeAddForm/Input/TreeFruitInput/TreeFruitInput.styled.ts
  src/components/features/Forest/TreeAddForm/TreeAddForm.styled.ts
  src/components/features/Forest/TreeAddForm/index.tsx
  src/components/features/MessageBox/EmptyMessage/EmptyMessage.styled.ts
  src/components/features/MessageBox/EmptyMessage/index.tsx
  src/components/features/MessageBox/MakingFruitPopup/MakingFruitPopup.styled.ts
  src/components/features/MessageBox/MakingFruitPopup/index.tsx
  src/components/features/MessageBox/MessageContent/index.tsx
  src/components/features/NoticeTree/AlertPopUp/AlertPopUp.styled.ts
  src/components/features/NoticeTree/AlertPopUp/AlertPopUp.type.ts
  src/components/features/NoticeTree/AlertPopUp/index.tsx
  src/components/features/NoticeTree/MessageBox/index.tsx
  src/components/features/NoticeTree/Tree/Tree.styled.ts
  src/components/features/NoticeTree/Tree/index.tsx
  src/components/features/NoticeTree/WateringButton/index.tsx
  src/components/layout/BackgroundArea/BackgroundArea.styled.ts
  src/components/layout/BackgroundArea/index.tsx
  src/components/shared/Modal/AlertModal/index.tsx
  src/components/shared/Modal/DeleteAlertModal/index.tsx
  src/components/shared/Modal/MediumAlertModal/MediumAlertModal.styled.ts
  src/components/shared/Modal/MediumAlertModal/index.tsx
  src/components/shared/Modal/SideDrawer/TreeFolderItem/TreeFolderItem.styled.ts
  src/components/shared/Modal/SideDrawer/index.tsx
  src/constants/forest.ts
  src/pages/MessageSender/index.tsx
  src/pages/NoticeTree/index.tsx
Labels: 🐛 버그

#149 [#142] Feat: og:image 추가
  index.html
Labels: ✨ 기능

#150 [#142] Fix : index.html 오타 수정
  index.html
Labels: 🐛 버그

#151 [#97] fix : 비로그인시 물주기, 나무숲 조회 구분 기능을 위한 레이아웃 퍼블릭/프라이빗 구분
  src/App.tsx
  src/apis/forest.ts
  src/apis/requester.ts
  src/components/features/Forest/TreeAddForm/index.tsx
  src/components/features/Forest/TreeList/TreeItem/index.tsx
  src/components/layout/Layout/Layout.tsx
  src/components/layout/PublicBottomNav/PublicBottomNav.styled.ts
  src/components/layout/PublicBottomNav/index.tsx
  src/components/layout/index.tsx
  src/components/shared/Routers.tsx
  src/hooks/useDrawer.ts
  src/pages/Forest/index.tsx
  src/pages/Landing/index.tsx
  src/pages/Login/index.tsx
  src/pages/MessageBox/index.tsx
  src/pages/MessageDetail/index.tsx
  src/pages/MessageSender/index.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/ProfileEdit/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/NoticeTree/index.tsx
  src/pages/PublicForest/Forest.styled.ts
  src/pages/PublicForest/index.tsx
  src/pages/TreeDetail/index.tsx
  src/pages/index.tsx
  src/types/forest.ts
Labels: ✨ 기능

#152 HotFix : 유저 나무 목록 관련 api 변경으로 인한 버그 수정
  src/assets/images/shared/not_found.png
  src/assets/images/shared/not_found.svg
  src/components/features/Forest/TreeAddForm/index.tsx
  src/components/shared/Modal/MovingFolderModal/index.tsx
  src/pages/MyPage/ProfileEdit/index.tsx
  src/pages/NotFound/NotFound.styled.ts
  src/pages/NotFound/index.tsx
Labels: :ambulance: Hotfix

#154 [#153] 나무 숲, 물 주기 비로그인 로직 수정
  src/apis/forest.ts
  src/components/features/Forest/TreeList/index.tsx
  src/pages/MessageSender/index.tsx
  src/pages/PublicForest/Forest.styled.ts
  src/pages/PublicForest/index.tsx
Labels: 🐛 버그, ✨ 기능

#160 [#155][#156][#157][#158][#159] 버그 리포트 개선
  src/App.tsx
  src/assets/images/trees/apple.png
  src/assets/images/trees/blueberry.png
  src/assets/images/trees/grape.png
  src/assets/images/trees/lemon.png
  src/assets/images/trees/orange.png
  src/assets/images/trees/strawberry.png
  src/components/features/Forest/TreeList/TreeItem/TreeItem.styled.ts
  src/components/features/Forest/TreeList/index.tsx
  src/components/features/MessageSender/MessageInput/MessageInput.styled.ts
  src/components/features/MyPage/MyContents/MyContents.tsx
  src/components/features/NoticeTree/MessageBox/MessageBox.styled.ts
  src/components/shared/Chip/MessageChip/MessageChip.styled.ts
  src/components/shared/Modal/ErrorToast/ErrorToast.styled.ts
  src/components/shared/Modal/SideDrawer/index.tsx
  src/components/shared/Toast/Toast.styled.ts
  src/hooks/useDrawer.ts
  src/pages/Forest/Forest.styled.ts
  src/pages/Forest/index.tsx
  src/pages/MessageDetail/MessageDetail.styled.ts
  src/pages/MessageSender/MessageSender.styled.ts
  src/pages/MessageSender/index.tsx
  src/pages/PublicForest/index.tsx
  src/pages/TreeDetail/index.tsx
  src/styles/GlobalStyle.tsx
Labels: 🐛 버그, 🎨 UI, ♻️ 리팩토링

#161 fix : 모바일 레이아웃 스크롤 현상 개선 & 나무 열매 영역 반응형 변경
  src/App.tsx
  src/components/features/Forest/TreeAddForm/TreeAddForm.styled.ts
  src/components/features/NoticeTree/Tree/index.tsx
  src/components/layout/Layout/Layout.styled.ts
  src/components/shared/Modal/SideDrawer/SideDrawer.styled.ts
  src/pages/Forest/Forest.styled.ts
  src/pages/Landing/Landing.styled.ts
  src/pages/Login/Login.styled.ts
  src/pages/MessageBox/MessageBox.styled.ts
  src/pages/MessageDetail/MessageDetail.styled.ts
  src/pages/MessageSender/MessageSender.styled.ts
  src/pages/MyPage/MyPage.styled.ts
  src/pages/MyPage/ProfileEdit/ProfileEdit.styled.ts
  src/pages/NotFound/NotFound.styled.ts
  src/pages/NoticeTree/NoticeTree.styled.ts
  src/pages/TreeDetail/TreeDetail.styled.ts
  src/styles/GlobalStyle.tsx
Labels: 🎨 UI

#163 [#162] Fix: 나무 삭제 경고창 삭제 대상 텍스트 더미데이터 -> 타켓 나무 텍스트로 변경
  src/components/shared/Modal/DeleteAlertModal/DeleteAlertModal.type.ts
  src/components/shared/Modal/SideDrawer/index.tsx
Labels: 🐛 버그

#165 [#164] Fix: 나무 숲, 물 주기 일부 위치 간격 수정
  src/components/features/Forest/TreeList/TreeItemAdd/TreeItemAdd.styled.ts
  src/components/features/Forest/TreeList/TreeItemAdd/index.tsx
  src/components/features/MessageSender/AnonymousCheckBox/AnonymousCheckBox.styled.ts
  src/components/features/MessageSender/AnonymousCheckBox/index.tsx
  src/components/features/MessageSender/MessageInput/MessageInput.styled.ts
  src/components/features/MessageSender/MessageInput/index.tsx
  src/pages/Forest/Forest.styled.ts
Labels: 🎨 UI
