Repository YAPP-Github/20th-Web-Team-1-FE, pull requests merged in 2022-07, with the labels that each got.

#19 Feat : 마이페이지 디자인 변경
  src/components/features/MyPage/Badge/Badge.styled.ts
  src/components/features/MyPage/Badge/Badge.tsx
  src/components/features/MyPage/MyContents/MyContents.styled.ts
  src/components/features/MyPage/MyContents/MyContents.tsx
  src/components/features/MyPage/MyInfo/MyInfo.styled.ts
  src/components/features/MyPage/MyInfo/MyInfo.tsx
  src/components/features/MyPage/MySetting/MySetting.styled.ts
  src/components/features/MyPage/MySetting/MySetting.tsx
  src/components/features/MyPage/index.ts
  src/components/layout/BottomNav/BottomNav.styled.ts
  src/components/layout/Layout/Layout.styled.ts
  src/constants/badge.ts
  src/pages/MyPage/MyPage.styled.ts
  src/pages/MyPage/MyPage.tsx
Labels: enhancement

#21 Feat : 메시지함 사이드 서랍 컴포넌트 스타일링
  index.html
  src/assets/images/messages/delete.svg
  src/assets/images/messages/edit.svg
  src/assets/images/messages/lock.svg
  src/assets/images/messages/see_more.svg
  src/components/shared/Modal/ModalFrame.styled.ts
  src/components/shared/Modal/ModalFrame.tsx
  src/components/shared/Modal/ModalPortal.tsx
  src/components/shared/Modal/SideDrawer/MenuMoreModal/MenuMoreModal.styled.ts
  src/components/shared/Modal/SideDrawer/MenuMoreModal/MenuMoreModalView.tsx
  src/components/shared/Modal/SideDrawer/MenuMoreModal/index.tsx
  src/components/shared/Modal/SideDrawer/MenuMoreModal/type.ts
  src/components/shared/Modal/SideDrawer/SideDrawer.styled.ts
  src/components/shared/Modal/SideDrawer/SideDrawerView.tsx
  src/components/shared/Modal/SideDrawer/TreeFolderItem/TreeFolderItem.styled.ts
  src/components/shared/Modal/SideDrawer/TreeFolderItem/TreeFolderItemView.tsx
  src/components/shared/Modal/SideDrawer/TreeFolderItem/index.tsx
  src/components/shared/Modal/SideDrawer/index.tsx
  src/components/shared/Modal/SideDrawer/type.ts
  src/components/shared/Modal/type.ts
  src/components/shared/Routers.tsx
  src/pages/Message/Message.styled.ts
  src/pages/Message/MessageView.tsx
  src/pages/Message/index.tsx
  src/pages/Message/type.ts
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/types/import-emotion.d.ts
Labels: enhancement

#28 Feat : api 메서드 구조 설계
  .gitignore
  src/apis/index.ts
  src/apis/messages.ts
  src/apis/requester.ts
  src/constants/api.ts
  src/utils/local-storage.ts
Labels: enhancement

#35 Feat : 로그인 기능 추가
  src/apis/auth.ts
  src/apis/requester.ts
  src/constants/api.ts
  src/pages/Login/index.tsx
  src/pages/Login/useLogin.ts
  src/pages/MessageDetail/MessageDetail.tsx
Labels: ✨ 기능

#36 Refactor: 스타일링 컨벤션 방식 변경 #34
  src/components/features/Trees/TreeAddForm/Input/TreeFruitInput/TreeFruitInput.styled.ts
  src/components/features/Trees/TreeAddForm/Input/TreeFruitInput/index.tsx
  src/components/features/Trees/TreeAddForm/TreeAddForm.styled.ts
  src/components/features/Trees/TreeAddForm/index.tsx
  src/components/features/Trees/TreeList/TreeItem/index.tsx
  src/components/features/Trees/TreeList/TreeItemAdd/TreeItemAdd.styled.ts
  src/components/features/Trees/TreeList/TreeItemAdd/TreeItemAdd.type.ts
  src/components/features/Trees/TreeList/TreeItemAdd/index.tsx
  src/components/features/Trees/TreeList/index.tsx
  src/components/shared/Button/index.tsx
  src/components/shared/Modal/SideDrawer/SideDrawer.styled.ts
  src/components/shared/Modal/SideDrawer/TreeFolderItem/TreeFolderItem.styled.ts
  src/components/shared/Modal/SideDrawer/TreeFolderItem/index.tsx
  src/components/shared/Modal/SideDrawer/index.tsx
  src/pages/MessageSender/index.tsx
  src/pages/Trees/index.tsx
Labels: ♻️ 리팩토링

#38 [#37] Feat: 나무 열매 렌더링
  src/assets/images/trees/orange.svg
  src/components/features/Trees/TreeAddForm/Input/TreeFruitInput/TreeFruitInput.type.ts
  src/components/features/Trees/TreeAddForm/Input/TreeFruitInput/index.tsx
  src/components/features/Trees/TreeAddForm/TreeAddForm.styled.ts
  src/components/features/Trees/TreeAddForm/TreeAddForm.type.ts
  src/components/features/Trees/TreeAddForm/index.tsx
  src/components/features/Trees/TreeList/TreeItem/TreeItem.type.ts
  src/components/features/Trees/TreeList/TreeItem/index.tsx
  src/components/features/Trees/TreeList/TreeList.type.ts
  src/components/features/Trees/TreeList/index.tsx
  src/constants/forest.ts
  src/constants/tree.ts
  src/pages/Trees/index.tsx
Labels: 🎨 UI

#48 [#47] Remove: 메시지함 페이지 디렉터리 수정
  src/pages/Message/Message.styled.ts
  src/pages/Message/MessageView.tsx
  src/pages/Message/index.tsx
  src/pages/Message/type.ts
Labels: ♻️ 리팩토링

#45 [#30] Feat : 내 정보 조회 기능 추가
  src/App.tsx
  src/apis/users.ts
  src/components/features/MyPage/MyInfo/MyInfo.tsx
  src/constants/api.ts
  src/hooks/useInput.ts
  src/index.tsx
  src/pages/Login/useLogin.ts
  src/pages/MyPage/ProfileEdit/index.tsx
  src/stores/index.ts
  src/stores/user.ts
  src/types/user.ts
Labels: ✨ 기능

#49 [#46] Feat: 물 주기 완료 모달 UI 구현
  src/components/shared/Modal/ModalFrame.styled.ts
  src/components/shared/Modal/ModalFrame.tsx
  src/components/shared/Modal/SuccessModal/SuccessModal.styled.ts
  src/components/shared/Modal/SuccessModal/SuccessModal.type.ts
  src/components/shared/Modal/SuccessModal/index.tsx
  src/components/shared/Modal/type.ts
  src/components/shared/index.tsx
  src/pages/MessageSender/MessageSender.styled.ts
  src/pages/MessageSender/index.tsx
Labels: 🎨 UI, ✨ 기능

#51 [#23] Feat : 로그아웃 기능 추가
  src/App.tsx
  src/apis/auth.ts
  src/components/features/MyPage/MyContents/MyContents.tsx
  src/constants/api.ts
  src/pages/Login/useLogin.ts
Labels: ✨ 기능

#53 [#40] Feat : 메세지함 열매 맺기 UI작업
  src/components/features/MessageBox/BottomButtons/BottomButtons.styled.ts
  src/components/features/MessageBox/BottomButtons/BottomButtons.type.ts
  src/components/features/MessageBox/BottomButtons/index.tsx
  src/components/features/MessageBox/MakingFruitMenu/MakingFruitMenu.styled.ts
  src/components/features/MessageBox/MakingFruitMenu/MakingFruitMenu.type.ts
  src/components/features/MessageBox/MakingFruitMenu/index.tsx
  src/components/features/MessageBox/MakingFruitPopup/MakingFruitPopup.styled.ts
  src/components/features/MessageBox/MakingFruitPopup/index.tsx
  src/components/features/MessageBox/MessageCheckBox/MessageCheckBox.styled.ts
  src/components/features/MessageBox/MessageContent/MessageContent.styled.ts
  src/components/features/MessageBox/MessageContent/MessageContent.type.ts
  src/components/features/MessageBox/MessageContent/index.tsx
  src/components/features/MessageBox/MessageMenu/MessageMenu.styled.ts
  src/components/features/MessageBox/MessageMenu/MessageMenu.type.ts
  src/components/features/MessageBox/MessageMenu/index.tsx
  src/components/features/MessageBox/index.ts
  src/pages/MessageBox/MessageBox.styled.ts
  src/pages/MessageBox/index.tsx
  src/styles/theme.ts
  src/types/import-emotion.d.ts
Labels: 🎨 UI, ✨ 기능

#55 [#50] Feat: 물 주기 폴더 선택 박스 UI 구현
  .gitignore
  src/assets/images/messageSender/arrow.svg
  src/components/features/MessageSender/FolderSelect/FolderSelect.styled.ts
  src/components/features/MessageSender/FolderSelect/FolderSelect.type.ts
  src/components/features/MessageSender/FolderSelect/index.tsx
  src/components/features/Trees/TreeList/TreeItem/TreeItem.type.ts
  src/components/features/Trees/TreeList/TreeItem/index.tsx
  src/components/features/Trees/TreeList/TreeItemAdd/index.tsx
  src/components/layout/BottomNav/BottomNav.tsx
  src/components/shared/Modal/SideDrawer/index.tsx
  src/components/shared/Routers.tsx
  src/pages/MessageSender/index.tsx
  src/pages/Trees/index.tsx
Labels: 🎨 UI

#57 [#56] Feat: 메시지함 삭제 모달 UI
  src/components/shared/Modal/AlertModalFrame/AlertModalFrame.styled.ts
  src/components/shared/Modal/AlertModalFrame/AlertModalFrame.type.ts
  src/components/shared/Modal/AlertModalFrame/index.tsx
  src/components/shared/Modal/DeleteAlertModal/DeleteAlertModal.styled.ts
  src/components/shared/Modal/DeleteAlertModal/DeleteAlertModal.type.ts
  src/components/shared/Modal/DeleteAlertModal/index.tsx
  src/components/shared/Modal/ModalFrame.styled.ts
  src/components/shared/Modal/ModalFrame.tsx
  src/components/shared/Modal/ModalFrame.type.ts
  src/components/shared/Modal/SuccessModal/SuccessModal.styled.ts
  src/components/shared/Modal/SuccessModal/index.tsx
  src/pages/MessageBox/index.tsx
Labels: 🎨 UI

#59 [#58] Feat: 사이드바 더보기 박스 구현
  src/components/shared/Modal/EditFolderMoreFrame/EditFolderMoreFrame.styled.ts
  src/components/shared/Modal/EditFolderMoreFrame/EditFolderMoreFrame.type.ts
  src/components/shared/Modal/EditFolderMoreFrame/index.tsx
  src/components/shared/Modal/ModalFrame.styled.ts
  src/components/shared/Modal/SideDrawer/EditFolderMoreModal/EditFolderMoreModal.styled.ts
  src/components/shared/Modal/SideDrawer/EditFolderMoreModal/EditFolderMoreModal.type.ts
  src/components/shared/Modal/SideDrawer/EditFolderMoreModal/index.tsx
  src/components/shared/Modal/SideDrawer/MenuMoreModal/MenuMoreModal.styled.ts
  src/components/shared/Modal/SideDrawer/MenuMoreModal/MenuMoreModal.type.ts
  src/components/shared/Modal/SideDrawer/MenuMoreModal/index.tsx
  src/components/shared/Modal/SideDrawer/SideDrawer.styled.ts
  src/components/shared/Modal/SideDrawer/SideDrawer.type.ts
  src/components/shared/Modal/SideDrawer/TreeFolderItem/TreeFolderItem.styled.ts
  src/components/shared/Modal/SideDrawer/TreeFolderItem/TreeFolderItem.type.ts
  src/components/shared/Modal/SideDrawer/TreeFolderItem/index.tsx
  src/components/shared/Modal/SideDrawer/index.tsx
  src/components/shared/Routers.tsx
  src/pages/MessageBox/index.tsx
Labels: 🎨 UI, ✨ 기능

#61 [#60] 메시지함 사이드바 유저 프로필 부분 API 데이터로 연결
  src/components/shared/Modal/SideDrawer/SideDrawer.type.ts
  src/components/shared/Modal/SideDrawer/index.tsx
  src/pages/MessageBox/index.tsx
Labels: ✨ 기능

#64 [#62] Feat : 마이페이지 하단 서비스 정책 영역 추가
  src/apis/messages.ts
  src/assets/images/layout/betree_logo.svg
  src/components/features/MyPage/MyContents/MyContents.styled.ts
  src/components/features/MyPage/ServicePolicy/ServicePolicy.styled.ts
  src/components/features/MyPage/ServicePolicy/index.tsx
  src/components/layout/Header/Header.styled.ts
  src/components/layout/Header/Header.tsx
  src/pages/MyPage/MyPage.styled.ts
  src/pages/MyPage/MyPage.tsx
Labels: 🐛 버그, 🎨 UI, ✨ 기능

#67 [#40] [#41] [#42] [#43] Feat : 메세지함 관련 api연결
  src/apis/forest.ts
  src/apis/messages.ts
  src/apis/noticeTree.ts
  src/assets/images/messages/delete_icon.svg
  src/components/features/MessageBox/BottomButtons/BottomButtons.type.ts
  src/components/features/MessageBox/BottomButtons/index.tsx
  src/components/features/MessageBox/MakingFruitMenu/MakingFruitMenu.type.ts
  src/components/features/MessageBox/MakingFruitMenu/index.tsx
  src/components/features/MessageBox/MakingFruitPopup/MakingFruitPopup.styled.ts
  src/components/features/MessageBox/MessageContent/MessageContent.styled.ts
  src/components/features/MessageBox/MessageContent/index.tsx
  src/components/features/MessageBox/MessageMenu/MessageMenu.type.ts
  src/components/features/MessageBox/MessageMenu/index.tsx
  src/components/shared/Modal/AlertModal/AlertModal.styled.ts
  src/components/shared/Modal/AlertModal/AlertModal.type.ts
  src/components/shared/Modal/AlertModal/index.tsx
  src/components/shared/Modal/MovingFolderModal/MovingFolderModal.styled.ts
  src/components/shared/Modal/MovingFolderModal/MovingFolderModal.type.ts
  src/components/shared/Modal/MovingFolderModal/index.tsx
  src/components/shared/Routers.tsx
  src/constants/api.ts
  src/pages/MessageBox/MessageBox.styled.ts
  src/pages/MessageBox/MessageBox.type.ts
  src/pages/MessageBox/index.tsx
  src/pages/MessageDetail/MessageDetail.styled.ts
  src/pages/MessageDetail/MessageDetail.tsx
  src/stores/messageBox.ts
  src/types/forest.ts
  src/types/message.ts
Labels: 🎨 UI, ✨ 기능

#74 [#72] Feat: 나무 숲 조회 기능 API 연결
  src/apis/forest.ts
  src/components/features/Forest/TreeAddForm/Input/TreeFruitInput/TreeFruitInput.styled.ts
  src/components/features/Forest/TreeAddForm/Input/TreeFruitInput/TreeFruitInput.type.ts
  src/components/features/Forest/TreeAddForm/Input/TreeFruitInput/index.tsx
  src/components/features/Forest/TreeAddForm/Input/TreeNameInput/TreeNameInput.styled.ts
  src/components/features/Forest/TreeAddForm/Input/TreeNameInput/TreeNameInput.type.ts
  src/components/features/Forest/TreeAddForm/Input/TreeNameInput/index.tsx
  src/components/features/Forest/TreeAddForm/TreeAddForm.styled.ts
  src/components/features/Forest/TreeAddForm/TreeAddForm.type.ts
  src/components/features/Forest/TreeAddForm/index.tsx
  src/components/features/Forest/TreeList/TreeItem/TreeItem.styled.ts
  src/components/features/Forest/TreeList/TreeItem/TreeItem.type.ts
  src/components/features/Forest/TreeList/TreeItem/index.tsx
  src/components/features/Forest/TreeList/TreeItemAdd/TreeItemAdd.styled.ts
  src/components/features/Forest/TreeList/TreeItemAdd/index.tsx
  src/components/features/Forest/TreeList/TreeList.styled.ts
  src/components/features/Forest/TreeList/TreeList.type.ts
  src/components/features/Forest/TreeList/index.tsx
  src/components/features/Trees/TreeList/TreeItem/TreeItem.type.ts
  src/components/features/Trees/TreeList/TreeList.type.ts
  src/components/shared/Modal/MovingFolderModal/index.tsx
  src/components/shared/Routers.tsx
  src/pages/Forest/Forest.styled.ts
  src/pages/Forest/index.tsx
  src/pages/index.tsx
  src/types/forest.ts
Labels: ✨ 기능, ♻️ 리팩토링

#77 [68] [69] 나무 상세페이지 UI 구현 / API 연결 및 기타 로직 수정
  src/apis/forest.ts
  src/apis/messages.ts
  src/components/features/Forest/TreeList/TreeItem/index.tsx
  src/components/features/MessageBox/BottomButtons/index.tsx
  src/components/features/MessageBox/MakingFruitMenu/index.tsx
  src/components/features/MessageBox/MessageContent/index.tsx
  src/components/features/MessageBox/MessageMenu/index.tsx
  src/components/features/MessageBox/index.ts
  src/components/features/MessageDetail/MessageDetailHeader/index.tsx
  src/components/features/MessageDetail/index.ts
  src/components/features/NoticeTree/AlertPopUp/index.tsx
  src/components/features/NoticeTree/WateringButton/index.tsx
  src/components/shared/Modal/MovingFolderModal/index.tsx
  src/components/shared/Routers.tsx
  src/components/shared/index.tsx
  src/pages/MessageBox/MessageBox.styled.ts
  src/pages/MessageBox/index.tsx
  src/pages/MessageDetail/MessageDetail.tsx
  src/pages/MessageDetail/index.tsx
  src/pages/TreeDetail/TreeDetail.styled.ts
  src/pages/TreeDetail/TreeDetail.type.ts
  src/pages/TreeDetail/index.tsx
  src/pages/TreeDetail/useTreeDetail.ts
  src/pages/index.tsx
  src/stores/messageBox.ts
  src/types/forest.ts
Labels: 🎨 UI, ✨ 기능, ♻️ 리팩토링

#81 [#54] Feat : 프로필 수정 기능 추가
  src/apis/users.ts
  src/constants/api.ts
  src/pages/MyPage/ProfileEdit/index.tsx
Labels: ✨ 기능

#82 [#73][#79][#80] Feat: 나무 추가,수정,삭제 API 연결
  src/apis/forest.ts
  src/components/features/Forest/TreeAddForm/Input/TreeNameInput/TreeNameInput.styled.ts
  src/components/features/Forest/TreeAddForm/Input/TreeNameInput/TreeNameInput.type.ts
  src/components/features/Forest/TreeAddForm/Input/TreeNameInput/index.tsx
  src/components/features/Forest/TreeAddForm/index.tsx
  src/components/features/Forest/TreeList/index.tsx
  src/components/features/MessageBox/MessageMenu/index.tsx
  src/components/shared/Modal/DeleteAlertModal/DeleteAlertModal.styled.ts
  src/components/shared/Modal/DeleteAlertModal/index.tsx
  src/components/shared/Modal/MovingFolderModal/index.tsx
  src/components/shared/Modal/SideDrawer/SideDrawer.type.ts
  src/components/shared/Modal/SideDrawer/TreeFolderItem/TreeFolderItem.styled.ts
  src/components/shared/Modal/SideDrawer/TreeFolderItem/TreeFolderItem.type.ts
  src/components/shared/Modal/SideDrawer/TreeFolderItem/index.tsx
  src/components/shared/Modal/SideDrawer/index.tsx
  src/constants/forest.ts
  src/pages/Forest/index.tsx
  src/pages/MessageBox/index.tsx
Labels: 🎨 UI, ✨ 기능

#85 [#83][#84] Feat: 물 주기(=메시지 보내기) 기능 구현
  src/apis/messages.ts
  src/components/features/MessageSender/FolderSelect/FolderSelect.type.ts
  src/components/features/MessageSender/FolderSelect/index.tsx
  src/components/features/MessageSender/MessageInput/MessageInput.type.ts
  src/components/features/MessageSender/MessageInput/index.tsx
  src/components/features/NoticeTree/WateringButton/index.tsx
  src/components/shared/Routers.tsx
  src/constants/messageSender.ts
  src/pages/MessageSender/index.tsx
  src/pages/TreeDetail/index.tsx
  src/pages/TreeDetail/useTreeDetail.ts
  src/types/message.ts
Labels: ✨ 기능

#87 [#86] Fix: 나무 편집 treeId Parameter 받아오는 로직 수정
  src/components/features/Forest/TreeAddForm/index.tsx
  src/components/shared/Modal/SideDrawer/SideDrawer.type.ts
  src/components/shared/Modal/SideDrawer/index.tsx
  src/pages/MessageBox/index.tsx
Labels: 🐛 버그

#89 Fix : 알림나무 UI 수정 및 API 명명법 변경
  src/apis/forest.ts
  src/apis/messages.ts
  src/assets/images/noticeTree/cancel_icon.svg
  src/assets/images/shared/tree.svg
  src/components/features/MessageBox/BottomButtons/index.tsx
  src/components/features/MessageBox/MessageContent/MessageContent.styled.ts
  src/components/features/NoticeTree/AlertPopUp/AlertPopUp.styled.ts
  src/components/features/NoticeTree/AlertPopUp/AlertPopUp.type.ts
  src/components/features/NoticeTree/AlertPopUp/index.tsx
  src/components/features/NoticeTree/Clouds/Clouds.styled.ts
  src/components/features/NoticeTree/MessageBox/MessageBox.styled.ts
  src/components/features/NoticeTree/MessageBox/index.tsx
  src/components/features/NoticeTree/Tree/Tree.styled.ts
  src/components/features/NoticeTree/Tree/Tree.type.ts
  src/components/features/NoticeTree/Tree/index.tsx
  src/components/features/NoticeTree/WateringButton/index.tsx
  src/components/shared/DefaultButton/DefaultButton.styled.ts
  src/components/shared/Modal/MovingFolderModal/index.tsx
  src/pages/MessageBox/index.tsx
  src/pages/MessageDetail/index.tsx
  src/pages/NoticeTree/NoticeTree.type.ts
  src/pages/NoticeTree/index.tsx
  src/pages/NoticeTree/useNoticeMessages.ts
  src/pages/TreeDetail/index.tsx
  src/pages/TreeDetail/useTreeDetail.ts
Labels: 🎨 UI, ♻️ 리팩토링

#90 [#88] Fix: 나무 숲 조회(GET) API 에러 해결
  src/components/features/Forest/TreeAddForm/index.tsx
  src/components/features/MessageBox/MessageMenu/index.tsx
  src/components/shared/Modal/MovingFolderModal/index.tsx
  src/pages/Forest/index.tsx
  src/pages/MessageBox/index.tsx
  src/pages/MessageSender/index.tsx
Labels: ✨ 기능, ♻️ 리팩토링

#92 [#91] Fix: 물 주기 페이지 버그 수정
  src/components/features/MessageSender/MessageInput/MessageInput.styled.ts
  src/pages/MessageSender/index.tsx
Labels: 🐛 버그, 🎨 UI

#95 [#93] Fix: 메시지함 사이드바 흐름 변경
  src/components/shared/Modal/SideDrawer/TreeFolderItem/TreeFolderItem.styled.ts
  src/components/shared/Modal/SideDrawer/TreeFolderItem/TreeFolderItem.type.ts
  src/components/shared/Modal/SideDrawer/TreeFolderItem/index.tsx
  src/components/shared/Modal/SideDrawer/index.tsx
  src/pages/MessageBox/index.tsx
Labels: ✨ 기능

#96 [70] [76] [94] Feat : 사이드바 커스텀 훅 추가 , 메세지 즐겨찾기, 공통알림적용
  src/apis/messages.ts
  src/apis/requester.ts
  src/assets/images/messages/star.svg
  src/components/features/MessageBox/MessageCheckBox/MessageCheckBox.type.ts
  src/components/features/MessageBox/MessageContent/MessageContent.styled.ts
  src/components/features/MessageBox/MessageContent/MessageContent.type.ts
  src/components/features/MessageBox/MessageContent/index.tsx
  src/components/features/MessageBox/MessageMenu/MessageMenu.styled.ts
  src/components/features/MessageBox/MessageMenu/MessageMenu.type.ts
  src/components/features/MessageBox/MessageMenu/index.tsx
  src/components/features/MessageDetail/MessageDetailHeader/MessageDetailHeader.styled.ts
  src/components/features/MessageDetail/MessageDetailHeader/index.tsx
  src/components/shared/Modal/SideDrawer/SideDrawer.type.ts
  src/components/shared/Modal/SideDrawer/index.tsx
  src/constants/api.ts
  src/hooks/useDrawer.ts
  src/pages/MessageBox/index.tsx
  src/pages/MessageDetail/MessageDetail.styled.ts
  src/pages/MessageDetail/index.tsx
  src/types/message.ts
Labels: 🎨 UI, ✨ 기능, ♻️ 리팩토링

#100 [#99] Fix: 사이드 바 더보기 상자 렌더링 에러 버그 해결
  src/components/shared/Modal/SideDrawer/index.tsx
  src/hooks/useDrawer.ts
Labels: 🐛 버그

#103 [101] Chore : 나무 상세페이지 좌우 버튼 디자인 변경 및 사이드바 즐겨찾기 클릭시 버튼 닫힘 추가
  src/assets/images/trees/tree_left_button.svg
  src/assets/images/trees/tree_right_button.svg
  src/components/shared/Modal/SideDrawer/index.tsx
  src/hooks/useDrawer.ts
  src/pages/TreeDetail/TreeDetail.styled.ts
  src/pages/TreeDetail/index.tsx
Labels: ♻️ 리팩토링

#106 [#105] Fix: 클라이언트 - 서버 프로토콜 차이 문제, 임시 해결
  .gitignore
  index.html
Labels: 🚀 배포, 🌐 HTTP

#107 [#78] Feat : 메세지함 무한스크롤 추가
  src/apis/messages.ts
  src/assets/images/noticeTree/no_message.svg
  src/assets/images/shared/not_found.svg
  src/components/features/MessageBox/BottomButtons/index.tsx
  src/components/features/MessageBox/MessageContent/index.tsx
  src/components/features/MessageBox/MessageMenu/MessageMenu.type.ts
  src/components/features/MessageBox/MessageMenu/index.tsx
  src/components/features/MessageDetail/MessageDetailHeader/index.tsx
  src/components/features/NoticeTree/Clouds/index.tsx
  src/components/features/NoticeTree/Tree/index.tsx
  src/components/layout/Layout/Layout.tsx
  src/components/shared/Modal/AlertModalFrame/AlertModalFrame.styled.ts
  src/components/shared/Modal/AlertModalFrame/AlertModalFrame.type.ts
  src/components/shared/Modal/AlertModalFrame/index.tsx
  src/components/shared/Modal/MediumAlertModal/MediumAlertModal.styled.ts
  src/components/shared/Modal/MediumAlertModal/index.tsx
  src/components/shared/Modal/MovingFolderModal/MovingFolderModal.type.ts
  src/components/shared/Modal/MovingFolderModal/index.tsx
  src/components/shared/Modal/SmallAlertModal/SmallAlertModal.styled.ts
  src/components/shared/Modal/SmallAlertModal/SmallAlertModal.type.ts
  src/components/shared/Modal/SmallAlertModal/index.tsx
  src/components/shared/Routers.tsx
  src/components/shared/index.tsx
  src/pages/MessageBox/index.tsx
  src/pages/MessageDetail/index.tsx
  src/pages/NotFound/NotFound.styled.ts
  src/pages/NotFound/NotFound.type.ts
  src/pages/NotFound/index.tsx
  src/pages/NoticeTree/index.tsx
  src/pages/NoticeTree/useNoticeMessages.ts
  src/pages/TreeDetail/index.tsx
  src/pages/TreeDetail/useTreeDetail.ts
  src/pages/index.tsx
  src/stores/modal.ts
  src/types/message.ts
Labels: ✨ 기능, ♻️ 리팩토링

#110 [#108] 테스트 페이지 배포 & 클라이언트 서버 프로토콜 에러 해결
  index.html
  package.json
Labels: 🚀 배포

#112 [#111] Fix: day.js 라이브러리 Build 시 Cannot call a namespace 해결
  src/components/features/MessageBox/MessageContent/index.tsx
Labels: 🐛 버그, 🚀 배포

#117 fix : 메시지함 버그 수정 및 메세지함 메세지 없는 경우 ui 작업 추가
  src/assets/images/messages/empty_box_bee.svg
  src/assets/images/messages/empty_folder_bee.svg
  src/components/features/MessageBox/EmptyMessage/EmptyMessage.styled.ts
  src/components/features/MessageBox/EmptyMessage/index.tsx
  src/components/features/MessageBox/MessageContent/MessageContent.styled.ts
  src/components/features/MessageBox/MessageContent/index.tsx
  src/components/features/MessageBox/MessageMenu/MessageMenu.styled.ts
  src/components/features/MessageBox/index.ts
  src/components/features/MessageDetail/MessageDetailHeader/index.tsx
  src/components/features/NoticeTree/Tree/Tree.styled.ts
  src/components/shared/Modal/SideDrawer/SideDrawer.styled.ts
  src/components/shared/Modal/SideDrawer/index.tsx
  src/pages/MessageBox/MessageBox.styled.ts
  src/pages/MessageBox/index.tsx
  src/pages/MessageDetail/index.tsx
  src/pages/NoticeTree/index.tsx
Labels: 🐛 버그, 🎨 UI

#120 [#118] Feat : 토스트 알림 추가
  src/components/features/MyPage/MyContents/MyContents.tsx
  src/components/shared/Toast/Toast.styled.ts
  src/components/shared/Toast/index.tsx
Labels: 🎨 UI, ✨ 기능

#121 fix : 전체 에러 토스트 모달 처리
  src/apis/forest.ts
  src/apis/messages.ts
  src/apis/noticeTree.ts
  src/components/features/MessageBox/BottomButtons/BottomButtons.type.ts
  src/components/features/MessageBox/BottomButtons/index.tsx
  src/components/features/MessageBox/MakingFruitMenu/MakingFruitMenu.type.ts
  src/components/features/MessageBox/MakingFruitMenu/index.tsx
  src/components/features/MessageBox/MessageContent/MessageContent.styled.ts
  src/components/features/MessageBox/MessageContent/MessageContent.type.ts
  src/components/features/MessageBox/MessageContent/index.tsx
  src/components/features/MessageDetail/MessageDetailHeader/index.tsx
  src/components/shared/Modal/ErrorToast/ErrorToast.styled.ts
  src/components/shared/Modal/ErrorToast/index.tsx
  src/components/shared/Modal/MovingFolderModal/index.tsx
  src/components/shared/index.tsx
  src/pages/MessageBox/index.tsx
  src/pages/MessageDetail/MessageDetail.styled.ts
  src/pages/MessageDetail/index.tsx
  src/pages/NoticeTree/index.tsx
  src/pages/TreeDetail/index.tsx
  src/pages/TreeDetail/useTreeDetail.ts
  src/stores/modal.ts
Labels: ✨ 기능, ♻️ 리팩토링

#122 [#63] Feat: 랜딩페이지 UI 구현, 컨텐츠 영역, 백그라운드 영역 분할
  src/assets/images/appBackground/instagram.png
  src/assets/images/appBackground/landing_logo.svg
  src/assets/images/appBackground/orange_bee.svg
  src/assets/images/appBackground/skip.svg
  src/assets/images/landing/landing_tree.png
  src/components/features/MessageSender/FolderSelect/index.tsx
  src/components/features/MessageSender/MessageInput/index.tsx
  src/components/layout/BackgroundArea/BackgroundArea.styled.ts
  src/components/layout/BackgroundArea/index.tsx
  src/components/layout/Layout/Layout.styled.ts
  src/components/layout/Layout/Layout.tsx
  src/components/layout/index.tsx
  src/components/shared/Modal/ModalFrame.styled.ts
  src/components/shared/Modal/SideDrawer/SideDrawer.styled.ts
  src/components/shared/Routers.tsx
  src/constants/appBackground.ts
  src/pages/Landing/Landing.styled.ts
  src/pages/Landing/index.tsx
  src/pages/Login/useLogin.ts
  src/pages/MessageSender/index.tsx
  src/pages/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/types/import-emotion.d.ts
Labels: 🎨 UI, ✨ 기능

#124 [#123] Fix : esbuild dependency reinstall because Missing Package
  src/components/features/MessageSender/FolderSelect/index.tsx
  src/components/features/MessageSender/MessageInput/index.tsx
  src/components/layout/BackgroundArea/index.tsx
  src/pages/MessageSender/index.tsx
Labels: 🐛 버그, 🚀 배포

#126 [#125] Fix : 배포환경 URL 복사하기 url 변경
  src/components/features/MyPage/MyContents/MyContents.tsx
Labels: 🐛 버그

#128 Fix : 랜딩페이지 추가로 인한 스타일 조정
  src/components/features/Forest/TreeList/TreeItem/index.tsx
  src/components/features/NoticeTree/AlertPopUp/index.tsx
  src/components/features/NoticeTree/MessageBox/MessageBox.styled.ts
  src/components/features/NoticeTree/Tree/Tree.styled.ts
  src/components/shared/Modal/ErrorToast/index.tsx
  src/components/shared/Modal/ModalFrame.styled.ts
  src/components/shared/Routers.tsx
  src/pages/TreeDetail/index.tsx
  src/styles/GlobalStyle.tsx
Labels: ♻️ 리팩토링

#130 [#127] Fix : 물 주기, 나무 편집 모달 수정
  src/assets/images/shared/pencil.png
  src/components/features/Forest/TreeAddForm/Input/TreeNameInput/TreeNameInput.type.ts
  src/components/features/Forest/TreeAddForm/Input/TreeNameInput/index.tsx
  src/components/features/Forest/TreeAddForm/TreeAddForm.styled.ts
  src/components/features/Forest/TreeAddForm/index.tsx
  src/components/features/Forest/TreeList/TreeItem/index.tsx
  src/components/features/MessageSender/MessageInput/index.tsx
  src/components/shared/Modal/SideDrawer/TreeFolderItem/index.tsx
  src/components/shared/Modal/SuccessModal/SuccessModal.styled.ts
  src/components/shared/Modal/SuccessModal/SuccessModal.type.ts
  src/components/shared/Modal/SuccessModal/index.tsx
  src/pages/Forest/index.tsx
  src/pages/MessageSender/MessageSender.styled.ts
  src/pages/MessageSender/index.tsx
  src/types/forest.ts
Labels: 🎨 UI, ✨ 기능

#132 [#131] Fix : 하단 네비게이션 UI & 기타 버그 수정
  index.html
  src/components/features/Forest/TreeAddForm/TreeAddForm.styled.ts
  src/components/layout/BottomNav/BottomNav.tsx
Labels: 🐛 버그, 🎨 UI

#133 [#129] Fix : 알림나무, 메세지함 버그 개선
  src/apis/messages.ts
  src/components/features/MessageBox/BottomButtons/BottomButtons.type.ts
  src/components/features/MessageBox/BottomButtons/index.tsx
  src/components/features/MessageBox/MessageMenu/index.tsx
  src/components/features/NoticeTree/MessageBox/MessageBox.styled.ts
  src/pages/MessageBox/index.tsx
  src/pages/MessageDetail/MessageDetail.styled.ts
  src/pages/MessageDetail/index.tsx
  src/pages/TreeDetail/index.tsx
  src/pages/TreeDetail/useTreeDetail.ts
Labels: 🐛 버그, ♻️ 리팩토링

#134 [#119] Fix : 프로필 수정 페이지에서 기존 이미지
  src/pages/MyPage/ProfileEdit/ProfileEdit.styled.ts
  src/pages/MyPage/ProfileEdit/index.tsx
Labels: 🐛 버그

#141 [#137][#138][#139][#140] 버그레포트 개선
  src/apis/messages.ts
  src/components/features/MessageBox/MessageContent/index.tsx
  src/components/features/NoticeTree/Clouds/index.tsx
  src/components/features/NoticeTree/Tree/Tree.styled.ts
  src/components/features/NoticeTree/Tree/Tree.type.ts
  src/components/features/NoticeTree/Tree/index.tsx
  src/components/layout/BottomNav/BottomNav.tsx
  src/components/layout/Header/Header.tsx
  src/pages/MessageDetail/MessageDetail.styled.ts
  src/pages/MessageDetail/index.tsx
  src/pages/TreeDetail/index.tsx
  src/types/forest.ts
  src/types/message.ts
Labels: 🐛 버그

#144 [#143] Fix : 나무 숲, 나무 편집 페이지 버그 수정
  index.html
  src/components/features/Forest/TreeAddForm/index.tsx
  src/components/features/Forest/TreeList/TreeList.styled.ts
Labels: 🐛 버그, 🎨 UI

#145 [#136] Fix : 마이페이지 여백 상대값으로 수정
  src/components/features/MyPage/MyInfo/MyInfo.styled.ts
  src/pages/MyPage/ProfileEdit/ProfileEdit.styled.ts
Labels: 🐛 버그, 🎨 UI
